### ISSUE TITLE
Software acknowledged at the end

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy-1.0-paper#104]
Currently, we acknowledge only one software package at the end of the paper:
```
Software: Astropy (The Astropy Collaboration et al. 2018)
```

Here are some questions (which may require a conversation with ApJ to resolve):

- Should `sunpy` be in this list?
- What other packages should be in this list, versus cited only in the text?
- Should citations be to project papers or to actual code (if cite-able)?

**Comment by wtbarnes** [comment]
From the AASTeX author guide,

> Authors should use the \software command to highlight the software packages that were used in the production of the article, especially those not mentioned in the text.

So I think this should really be everything: matplotlib, numpy, scipy, scikit-image, pfsspy, etc.

**Comment by mbobra** [comment]
100% agree with @wtbarnes
