### ISSUE TITLE
Figure 1 should be in color

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy-1.0-paper#119]
It looks a bit strange that Figure 1 is the only figure without color.

**Comment by ehsteve** [comment]
Figures should only use colors if necessary. I don't see how it is necessary for that figure.

**Comment by wtbarnes** [comment]
That's fair. I was just thinking aesthetically.

A few other minor nitpicks with that figure:

* the axes labels on the third panel should be capitalized (or the other two panels lower-case)
* the frames around both legends can be removed
* "Releases" -> "Release" on the top axes on the first two panels
* The the legend in the third panel should be all math mode, i.e. $N^{-0.34}$

These are not urgent obviously.

**Comment by ehsteve** [comment]
Addressed in #122. Check it out.
