### ISSUE TITLE
Cleanup acknowledgement and software section

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy-1.0-paper#132]
The acknowledgement section is still a bit messy and there is still a TODO in there for thanking a few organizations.

The software section should be consolidated into one `\software` tag and references should be provided wherever possible.

**Comment by hayesla** [comment]
we should also acknowledge Brian Dennis and Richard and whoever else offered copyediting to the paper :)

**Comment by ehsteve** [comment]
@hayesla I've already done that for Brian and Richard.

**Comment by wtbarnes** [comment]
add Bill Thompson as well

**Comment by wtbarnes** [comment]
Schwarts->Schwartz

**Comment by wtbarnes** [comment]
Line thanking SPD for committing to providing support for workshops and a prize
