### ISSUE TITLE
Add HEK position on map example (figure 3)

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy-1.0-paper#135]
Given that we show the HEK peak time on the GOES plot, perhaps we should also add the HEK position on the Map example. I would suggest that it only be added on the left-hand panel and not the right-hand. Thoughts @hayesla?

**Comment by ehsteve** [comment]
The HPC position provided by the SWPC in the HEK catalog is (715.5, -339.795).

**Comment by ehsteve** [comment]
@hayesla what do you think about this suggestion?

**Comment by hayesla** [comment]
this is a nice idea - I'll do it now
