### ISSUE TITLE
GOES time series plot and peek()

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy-1.0-paper#136]
Figure 2 does not use peek() and so we are not using the opportunity to show off the visualization aspect of time series. Peek() provides the goes class defined y axis.

**Comment by hayesla** [comment]
Well I feel like for figure worthy plots it better to use plot as you have more control over just using the peek() functionality - isn't peek rather actually inspecting the data?

**Comment by ehsteve** [comment]
Yes, you are right that peek is not really meant to be used to make figures. The thing that bothers me the most is the GOES class axis is not represented here. I'm mostly fine with not using peek(). It might be good to break out the function that adds that axis as a helper function in SunPy but that is a comment for another repo!

**Comment by hayesla** [comment]
That's true - we can add that in though - should we update the figure to this

![timeseries_example2](https://user-images.githubusercontent.com/4620298/62869294-91227d00-bce5-11e9-9669-6cb24c5ddc2e.png)
