### ISSUE TITLE
Fido and `drms`

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy-1.0-paper#150]
The paper is confusing/misleading about `drms` and its relationship to the core package.  The Fido section (4.1.1) takes credit for providing access to JSOC, but doesn't mention `drms` at all.  In the `drms` section (6.1), the description gives no indication that `drms` is actually a dependency of Fido's aforementioned JSOC capability.

**Comment by mbobra** [comment]
`drms` does not depend on Fido.

**Comment by ayshih** [comment]
Huh?  I'm saying that Fido depends on `drms` for JSOC capability.

**Comment by ehsteve** [comment]
This has not been resolved in the submitted version so keeping this open to fix when we get reviewer comments back.

**Comment by ehsteve** [comment]
In the proof, added a line to the dmrs package section at the end "\Fido depends on this package to enable it to access JSOC search results."  Also added text to the Fido section "thanks to the \package{drms} affiliated package see Section..."
