### ISSUE TITLE
Tag along as co-author if it's ok

### ISSUE THREAD

**Issue by kiendang** [sunpy/sunpy-1.0-paper#159]
## Details

* Given Name: Trung Kien

* Family Name: Dang

* Email: mail@kien.ai

* Affiliation: Saw Swee Hock School of Public Health, National University Health System, National University of Singapore, Singapore

* ORCID (if available): 0000-0001-7562-6495

## Contribution to the SunPy Community

Fixed minor bug related to image observation time.

**Comment by ehsteve** [comment]
Thank you and added you to through an edit to the proof.

**Comment by kiendang** [comment]
Sweet. Thank you!
