### ISSUE TITLE
Figure out a way to validate and compare our coordinate transformations for the paper

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy-1.0-paper#2]

**Comment by ehsteve** [comment]
What did @dpshelio do which compared all of the IDL codes to do this?

**Comment by ehsteve** [comment]
May be worth bringing in Bill Thompson to help with this.

**Comment by ehsteve** [comment]
@wafels has agreed to do this on our Telecon.

**Comment by ehsteve** [comment]
One possibility is to generate 10,000 random points on the Sun and convert them between HPC to HLG and compare the results similar to what was done in the astropy paper. I would also recommend that points above the surface of the Sun be includes (X, Y, Z) as well.

**Comment by wafels** [comment]
I spoke to Bill about this yesterday. We should be able to do comparisons of the solar coordinate transformations in SunPy and SSW.

**Comment by ehsteve** [comment]
Spice may also allow provide helio to helio transformations which could be checked against.

**Comment by ehsteve** [comment]
The plan is currently ignore this issue and leave it till later.

**Comment by ayshih** [comment]
Closing this issue because we now make clear that we check against the *Astronomical Almanac*
