### ISSUE TITLE
some issues about the abstract and Sections 1-4

### ISSUE THREAD

**Issue by mbobra** [sunpy/sunpy-1.0-paper#25]
Here are some issues about the abstract and Sections 1-4:

- [ ] @Cadair will write some words about the small grant from NumFOCUS.
- [x] We all need to decide whether we want to deposit our SEPs in Zenodo (x/ref sunpy/sunpy-SEP#33). My vote is yes.
- [x] We need to come up with a convention for referring to the sunpy core package -- as `SunPy` or `sunpy` -- and similarly for the other packages we reference.
- [x] @ehsteve Please let me know if the mission statement is correct. Otherwise, can you please let me know exactly what text to use?
- [x] @nabobalis Please write a caption for Figure 1.
We should figure out the answers to the following questions:
- [ ] Should we cite all previous versions of SunPy released on Zenodo? If we do this, they will all show up in ADS.
- [ ] Should the introduction include some words on what constitutes v1.0? (Or reference Section 11)?
- [x] Should we mention that we are collaborating with other heliophysics python developers and agreed to the Heliopython Standards?

**Comment by ehsteve** [comment]
Just do small PRs to fix these issues individually.

**Comment by ehsteve** [comment]
I'll take on issue number 2.

**Comment by ehsteve** [comment]
Decision is `sunpy` for the package and `SunPy` for the project.

**Comment by ehsteve** [comment]
Cite the Zenodo 1.0 release (and the bug fix) and then the zenodo `all` for all other releases. @Cadair can cite others if he wants.

**Comment by ehsteve** [comment]
@Cadair to add words about what constitutes v1.0.

**Comment by ehsteve** [comment]
I will add a citation to the PyHC standards document.

**Comment by ehsteve** [comment]
Relooked at the mission statement text and it looks fine @mbobra

**Comment by ehsteve** [comment]
Looks like astropy just uploads each APE to zenodo by hand to get their DOI. I'll do the same for us.

**Comment by ehsteve** [comment]
Moved open issues from this into individual issues (#79, #80, #81, #82).
