### ISSUE TITLE
Update the transform graph of our coordinate frames

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy-1.0-paper#3]
Something like this 
<img width="1326" alt="Screen Shot 2019-03-27 at 2 36 05 PM" src="https://user-images.githubusercontent.com/739053/55103089-31149c80-509e-11e9-91e1-b70db21d56dc.png">

**Comment by ehsteve** [comment]
The latest is available in this [gist](https://gist.github.com/Cadair/b1ca42092a29850c09bcf079df2f8087)

**Comment by ehsteve** [comment]
@Cadair could you add the code that generated that figure to the repo please?

**Comment by ayshih** [comment]
I'll take on updating this figure to make it consistent with the text that I wrote in #27
