### ISSUE TITLE
editing the file community.tex

### ISSUE THREAD

**Issue by mbobra** [sunpy/sunpy-1.0-paper#32]
Let's try to edit, prettify, and complete as much of the file community.tex as we reasonably can by this Friday (June 7) :sunny:

**Comment by mbobra** [comment]
I looked at this and am happy with the text. We can keep it as-is for the SPD. 

In the future, we should modify the following sentence: 

> As of the publication of this paper, the \sunpy community consists of 35 active developers, 111 contributors, and an average of approximately 200 commits to the code base on a monthly basis.

It looks like we have 113 contributors now. But I'm not sure how we classify someone as an active developer. Does anyone else know?

**Comment by wtbarnes** [comment]
I had just one minor comment on this section: there is a single subsection ("Participation") in this section. Unless there are other subsections to add, I would remove that subsection and just let all of the text fall under the "Community" section header.

**Comment by wtbarnes** [comment]
This is closed by #43 correct?
