### ISSUE TITLE
Figure styling

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy-1.0-paper#39]
Are we using the `setup_plot()` function or the matplotlibrc? These two are somewhat in conflict. 

Also the font in the figures should be roughly the same as that in the main body of the text.

**Comment by ehsteve** [comment]
I've been removing the `setup_plot()` as I agree that the `matplotlibrc` file is the accepted approach.

**Comment by wtbarnes** [comment]
Ok. Just wanted to make sure that was the consensus.

**Comment by wtbarnes** [comment]
I fixed several of these in #40 so I'm going to go ahead and close this.
