### ISSUE TITLE
Problem with differential rotation figure

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy-1.0-paper#48]
See sunpy/sunpy#3190. Creating this so we don't forget to address this one way or the other before publication. Also, the background on the lower panel should be black instead of white.

**Comment by wtbarnes** [comment]
The upstream problem in sunpy has now been moved to sunpy/sunpy#3226

**Comment by ehsteve** [comment]
This is a blocking issue.

**Comment by wtbarnes** [comment]
Once sunpy/sunpy#3245 is merged, I will fix the figure
