### ISSUE TITLE
Adding author

### ISSUE THREAD

**Issue by aringlis** [sunpy/sunpy-1.0-paper#69]
## Details

* Given Name: Andrew

* Family Name: Inglis

* Email: andrew.inglis@nasa.gov

* Affiliation: NASA Goddard Space Flight Center

* ORCID (if available): 0000-0003-0656-2437

## Contribution to the SunPy Community

Former member of the SunPy board ~2013-2017. Regular contributor in the <0.6 era, less so these days.

**Comment by ehsteve** [comment]
👍 added.
