### ISSUE TITLE
Add a figure that shows a transformation to astrophysical coordinates

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy-1.0-paper#7]

**Comment by ehsteve** [comment]
The best current idea is to show regulus using an eclipse photo as is done in the [solar eclipse repo](https://github.com/sunpy/solar-eclipse) and in [this notebook](https://github.com/sunpy/solar-eclipse/blob/master/notebooks/Processing%20your%20Eclipse%20Photo%20with%20SunPy.ipynb).

**Comment by ehsteve** [comment]
Better idea would be to overlay the star field shown here on a lasco image.

![C3-2008000](https://user-images.githubusercontent.com/739053/55812913-d164bb00-5ab9-11e9-982a-cb7f02ee2999.gif)

![cmeweek1_c3full](https://user-images.githubusercontent.com/739053/55812940-df1a4080-5ab9-11e9-833f-182bd46bce9e.gif)

**Comment by wafels** [comment]
We’re adding planet labels and PSP encounters on helioviewer.org that were calculated using sunpy, astropy, heliopy and spiceypy. We could just use a screenshot from helioviewer.

**Comment by Cadair** [comment]
Can we have that code in the example gallery please :grin:

**Comment by wafels** [comment]
I’ll post an example in the chat.

**Comment by ehsteve** [comment]
@wafels could you post it here instead so it is easier to find? Thanks.

**Comment by ehsteve** [comment]
[lasco_with_stars.pdf](https://github.com/sunpy/sunpy-1.0-paper/files/3069934/lasco_with_stars.pdf)

**Comment by ehsteve** [comment]
<img width="964" alt="Screen Shot 2019-04-11 at 1 53 22 PM" src="https://user-images.githubusercontent.com/739053/55979891-373f7700-5c61-11e9-96fb-f38ce1dd5a84.png">

**Comment by ehsteve** [comment]
This image was generated with this [code](https://gist.github.com/ehsteve/a6dba7d1e1a5a9204c7bab89e17666ac). The locations of the stars are not quite correct. Investigation is ongoing to determine why.

**Comment by ehsteve** [comment]
I've added the data file in a new [data directory](https://github.com/sunpy/sunpy-1.0-paper/tree/master/data)

**Comment by ayshih** [comment]
Your code needs to take into account that the observer is not at Earth.

I used SunSPICE to obtain SOHO's location at the time of this image, and here's code for the corresponding `SkyCoord`:
```python
>>> from astropy.coordinates import SkyCoord, CartesianRepresentation, HeliocentricTrueEcliptic

>>> soho_hae = CartesianRepresentation(-1.3602648e8, 55390609., 67729.814)*u.km
>>> soho = SkyCoord(soho_hae, frame=HeliocentricTrueEcliptic, obstime='2000-02-27 07:42:05.810')
```
You then need to feed `observer=soho` as a keyword argument any time you use `frames.Helioprojective`.

The difference is ~11 arcmin in longitude and ~2 arcmin in latitude:
```python
>>> from sunpy.coordinates import get_earth
>>> print(soho.heliographic_stonyhurst)
<SkyCoord (HeliographicStonyhurst: obstime=2000-02-27 07:42:05.810): (lon, lat, radius) in (deg, deg, km)
    (359.81847756, -7.15574196, 1.46871806e+08)>
>>> print(get_earth(soho.obstime))
<SkyCoord (HeliographicStonyhurst: obstime=2000-02-27 07:42:05.810): (lon, lat, radius) in (deg, deg, AU)
    (0., -7.18539121, 0.99025198)>
```

**Comment by wafels** [comment]
I have a heliopy based solution almost ready. It reads the soho spice kernels and will return in ICRS.

**Comment by Cadair** [comment]
I assume this data isn't in the header at all? I wonder if we should optionally import Heliopy in the SOHO source?

**Comment by wafels** [comment]
Here is my heliopy based solution to use the SOHO SPICE kernels.

Download and install my branch of heliopy that points to the SOHO SPICE
kernels and adapts heliopy to return a SkyCoord.  It's at

*https://github.com/wafels/heliopy/tree/spicecoordinates
<https://github.com/wafels/heliopy/tree/spicecoordinates>*

You'll also need to install cdflib and spiceypy - I did that using pip.
The following code snippet gives an example on how to setup heliopy to use
the SPICE kernels and return the position of SOHO in the HGS system.













*from sunpy.time import parse_timefrom sunpy.coordinates.frames import
HeliographicStonyhurstimport heliopy.spice as spiceimport
heliopy.data.spice as spicedatatime =
parse_time('2010-02-03')spice.setup_spice()kernels =
spicedata.get_kernel('soho')spice.furnish(kernels)target =
spice.Trajectory('SOHO')coordinate = target.coordinate(time)coordinate_hgs
= coordinate.transform_to(HeliographicStonyhurst)*

**Comment by wafels** [comment]
Also: https://github.com/wafels/heliopy/tree/spicecoordinates

**Comment by Cadair** [comment]
We can close this now right?
