### ISSUE TITLE
Adding as an author [Prateek]

### ISSUE THREAD

**Issue by prateekiiest** [sunpy/sunpy-1.0-paper#71]
## Details

* Given Name

Prateek Chanda

* Family Name

Chanda

* Email

prateekkol21@gmail.com

* Affiliation
Indian Institute of Engineering Science and Technology, India

* ORCID (if available)
http://orcid.org/0000-0002-7068-2866

## Contribution to the SunPy Community

* **[2017]** - Worked on bug reporting and enhancements for map class and sunpy website [inital phase]
* **[2018]**  Worked on adding new gallery examples and few fixes. Some initial work on sunkit.

Working on < 0.9 . Had not been much active since 1.0rc.

**Comment by mbobra** [comment]
Addressed by #73
