### ISSUE TITLE
Adding co-author

### ISSUE THREAD

**Issue by rajul** [sunpy/sunpy-1.0-paper#72]
## Details

* Given Name: Rajul (I only use a single name officially)

* Email: rajul09@gmail.com

* Affiliation: Indian Institute of Technology Kharagpur

* ORCID (if available): 0000-0003-3552-8799

## Contribution to the SunPy Community

* Fixed bugs and issues in the database module
* Developed plugins enabling use and visualization of solar data from within Ginga
* Reported and fixed bugs, and did some code cleanup
* Added unit tests to various modules in the framework

**Comment by ehsteve** [comment]
done.
