### ISSUE TITLE
Add information on small grant from NumFOCUS

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy-1.0-paper#80]

**Comment by mbobra** [comment]
Maybe we could add the following information:

The [NumFOCUS 2018 Annual Report](https://numfocus.org/wp-content/uploads/2019/04/NumFOCUS-Annual-Report-2018-FINAL.pdf) says that SunPy received a small grant for "Improving the Usability of SunPy’s Data Downloader." They disbursed $60k among 16 packages. I don't know exactly how much SunPy received (maybe @dpshelio knows), but $60k/16 = $3750. SunPy's total income in 2018 was $3120. (It was $265 in 2017).

**Comment by Cadair** [comment]
they gave us $3,000 for the grant.

**Comment by wtbarnes** [comment]
Should go in "Acknowledgement" section

**Comment by ehsteve** [comment]
Was this supposed to be addressed in your last PR or did I miss it @wtbarnes?

**Comment by ehsteve** [comment]
Added the following line to the proof "We acknowledge financial contributions from NumFocus for Improving the Usability of SunPy’s Data Downloader."
