### ISSUE TITLE
Add a paragraph to section 7 to discuss other components of sunpy.net

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy-1.0-paper#87]
This means putting back in the reference to helioviewer that was deleted as well as other things.

**Comment by wtbarnes** [comment]
Where is the old text about helioviewer that needs to be added back in? I cannot find it.

**Comment by wtbarnes** [comment]
@mbobra Can you reopen this? #110 was not ready to be merged. I should've marked it as a work in progress. Sorry!

**Comment by mbobra** [comment]
Sorry!

**Comment by ehsteve** [comment]
Isn't this ready to be closed now?

**Comment by wtbarnes** [comment]
Closed by #115
