### ISSUE TITLE
Order of panels in differential-rotation figure

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy-1.0-paper#98]
The order of the panels in the differential-rotation figure has always bothered me.  It's currently:

- (a) AIA image on 2014 Oct 20
- (b) AIA image on 2014 Oct 22
- (c) Differential rotation of (a) to 2014 Oct 22

I suggest swapping panels (b) and (c), so that we start with a Map, rotate it, and then show what the actual observation looks like.  Discuss.

**Comment by ehsteve** [comment]
Ha! this has also bothered me as well! I'll fix this.
